site_name: AWS .NET deployment tool
site_description: 'Deploy .NET applications on AWS'
site_url: 'https://aws.github.io/aws-dotnet-deploy/'
repo_name: 'aws/aws-dotnet-deploy'
repo_url: 'https://github.com/aws/aws-dotnet-deploy'
edit_uri: 'edit/main/site/content'
copyright: '&copy; 2022, Amazon Web Services, Inc. or its affiliates. All rights reserved.'
docs_dir: 'site/content'
site_dir: 'docs'

nav:
  - Overview: index.md
  - Documentation:
    - Getting started:
      - Pre-requisites: docs/getting-started/pre-requisites.md
      - How to install: docs/getting-started/installation.md
      - Set up credentials: docs/getting-started/setup-creds.md
      - Set up a custom workspace: docs/getting-started/custom-workspace.md
      - Deploy "Hello World": docs/getting-started/run-tool.md
    -  Support matrix: docs/support.md
    - Commands:
      - deploy: docs/commands/deploy.md
      - list-deployments: docs/commands/list.md
      - delete-deployment: docs/commands/delete.md
      - deployment-project: docs/commands/project.md
      - server-mode: docs/commands/server-mode.md
    - Docker support:
      - Dockerfile generation: docs/docker/docker-generation.md
      - Publishing a Docker image: docs/docker/publish-image.md
    - Deployment Projects:
       - Overview: docs/deployment-projects/index.md
       - Recipe File: docs/deployment-projects/recipe-file.md
       - CDK Project: docs/deployment-projects/cdk-project.md
    - Integrating with CI/CD: 
       - Overview: docs/cicd/cicd.md
       - Deployment Settings File: docs/cicd/deployment-settings-file.md
       - Deployment Recipes:
           - ... | flat
  - Tutorials:
    - Customizing deployment projects: tutorials/custom-project.md
  - Troubleshooting Guide:
    - troubleshooting-guide/index.md
    - Missing Dependencies: troubleshooting-guide/missing-dependencies.md
    - Docker Issues: troubleshooting-guide/docker-issues.md
  - Contributing to the project: contributing.md
  - FAQs: faq.md

theme:
  name: material
  custom_dir: site/overrides
  palette:
    primary: indigo
  font: false
  language: en
  features:
    - tabs
    - instant
  icon:
    logo: aws-logo-light
  favicon: assets/images/aws-logo-light.svg

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji

plugins:
    - search
    - awesome-pages